In [2]:
import sys,os
import numpy as np
sys.path.insert(0,'../scripts/')
from data_fetch import get_data
from data_cleaning_transformation import to_datatime,drop_duplicate,fill_missing_values,standard_scaler
from data_analysis import data_info,percent_missing,handset_manufacturer,top_handsets,total_ul_per_user,total_dl_per_user,total_data_vol,total_dur_per_user,mean_value,median_value,var_value,std_value,decile_value,plot_hist,plot_count,plot_bar,plot_heatmap,plot_box,plot_scatter,correlation_matrix,dem_reduction,plot_box_multi

In [3]:
data = get_data('data/Week1_challenge_data_source.csv','C:/Users/User/Desktop/Telecom-data-analysis','Week1_challenge_data_source_v1')

In [24]:
data.shape

(150001, 56)

In [5]:
data_info(data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

(None,
 ['Bearer Id',
  'Start',
  'Start ms',
  'End',
  'End ms',
  'Dur. (ms)',
  'IMSI',
  'MSISDN/Number',
  'IMEI',
  'Last Location Name',
  'Avg RTT DL (ms)',
  'Avg RTT UL (ms)',
  'Avg Bearer TP DL (kbps)',
  'Avg Bearer TP UL (kbps)',
  'TCP DL Retrans. Vol (Bytes)',
  'TCP UL Retrans. Vol (Bytes)',
  'DL TP < 50 Kbps (%)',
  '50 Kbps < DL TP < 250 Kbps (%)',
  '250 Kbps < DL TP < 1 Mbps (%)',
  'DL TP > 1 Mbps (%)',
  'UL TP < 10 Kbps (%)',
  '10 Kbps < UL TP < 50 Kbps (%)',
  '50 Kbps < UL TP < 300 Kbps (%)',
  'UL TP > 300 Kbps (%)',
  'HTTP DL (Bytes)',
  'HTTP UL (Bytes)',
  'Activity Duration DL (ms)',
  'Activity Duration UL (ms)',
  'Dur. (ms).1',
  'Handset Manufacturer',
  'Handset Type',
  'Nb of sec with 125000B < Vol DL',
  'Nb of sec with 1250B < Vol UL < 6250B',
  'Nb of sec with 31250B < Vol DL < 125000B',
  'Nb of sec with 37500B < Vol UL',
  'Nb of sec with 6250B < Vol DL < 31250B',
  'Nb of sec with 6250B < Vol UL < 37500B',
  'Nb of sec with Vol DL < 6250B',
  'Nb of sec with Vol UL < 1250B',
  'Social Media DL (Bytes)',
  'Social Media UL (Bytes)',
  'Google DL (Bytes)',
  'Google UL (Bytes)',
  'Email DL (Bytes)',
  'Email UL (Bytes)',
  'Youtube DL (Bytes)',
  'Youtube UL (Bytes)',
  'Netflix DL (Bytes)',
  'Netflix UL (Bytes)',
  'Gaming DL (Bytes)',
  'Gaming UL (Bytes)',
  'Other DL (Bytes)',
  'Other UL (Bytes)',
  'Total UL (Bytes)',
  'Total DL (Bytes)'])

In [6]:
percent_missing(data)

The dataset contains 12.5 % missing values.

In [7]:
data.isna().sum()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [8]:
to_datatime(data,'Start')

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,2019-04-04 12:01:00,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,1.585461e+07,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0
1,1.311448e+19,2019-04-09 13:04:00,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,2.024740e+07,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0
2,1.311448e+19,2019-04-09 17:42:00,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,1.972566e+07,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0
3,1.311448e+19,2019-04-10 00:31:00,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,2.138812e+07,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0
4,1.311448e+19,2019-04-12 20:10:00,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,1.525938e+07,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,2019-04-29 07:28:00,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,2019-04-29 07:28:00,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,2019-04-29 07:28:00,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,2019-04-29 07:28:00,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN

In [9]:
to_datatime(data,'End')

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,2019-04-04 12:01:00,770.0,2019-04-25 14:35:00,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,1.585461e+07,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0
1,1.311448e+19,2019-04-09 13:04:00,235.0,2019-04-25 08:15:00,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,2.024740e+07,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0
2,1.311448e+19,2019-04-09 17:42:00,1.0,2019-04-25 11:58:00,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,1.972566e+07,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0
3,1.311448e+19,2019-04-10 00:31:00,486.0,2019-04-25 07:36:00,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,2.138812e+07,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0
4,1.311448e+19,2019-04-12 20:10:00,565.0,2019-04-25 10:40:00,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,1.525938e+07,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,2019-04-29 07:28:00,451.0,2019-04-30 06:02:00,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,2019-04-29 07:28:00,483.0,2019-04-30 10:41:00,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,2019-04-29 07:28:00,283.0,2019-04-30 10:46:00,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,2019-04-29 07:28:00,696.0,2019-04-30 10:40:00,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN

In [10]:
drop_duplicate(data)

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,2019-04-04 12:01:00,770.0,2019-04-25 14:35:00,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,1.585461e+07,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0
1,1.311448e+19,2019-04-09 13:04:00,235.0,2019-04-25 08:15:00,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,2.024740e+07,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0
2,1.311448e+19,2019-04-09 17:42:00,1.0,2019-04-25 11:58:00,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,1.972566e+07,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0
3,1.311448e+19,2019-04-10 00:31:00,486.0,2019-04-25 07:36:00,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,2.138812e+07,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0
4,1.311448e+19,2019-04-12 20:10:00,565.0,2019-04-25 10:40:00,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,1.525938e+07,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,2019-04-29 07:28:00,451.0,2019-04-30 06:02:00,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,2019-04-29 07:28:00,483.0,2019-04-30 10:41:00,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,2019-04-29 07:28:00,283.0,2019-04-30 10:46:00,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,2019-04-29 07:28:00,696.0,2019-04-30 10:40:00,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN

In [11]:
handset_manufacturer(data)

Apple      59565
Samsung    40839
Huawei     34423
Name: Handset Manufacturer, dtype: int64

In [12]:
top_handsets(data,'Apple')

Apple iPhone 6S (A1688)    9419
Apple iPhone 6 (A1586)     9023
Apple iPhone 7 (A1778)     6326
Apple iPhone Se (A1723)    5187
Apple iPhone 8 (A1905)     4993
Name: Handset Type, dtype: int64

In [13]:
top_handsets(data,'Huawei')

Huawei B528S-23A                  19752
Huawei E5180                       2079
Huawei P20 Lite Huawei Nova 3E     2021
Huawei P20                         1480
Huawei Y6 2018                      997
Name: Handset Type, dtype: int64

In [14]:
top_handsets(data,'Samsung')

Samsung Galaxy S8 (Sm-G950F)    4520
Samsung Galaxy A5 Sm-A520F      3724
Samsung Galaxy J5 (Sm-J530)     3696
Samsung Galaxy J3 (Sm-J330)     3484
Samsung Galaxy S7 (Sm-G930X)    3199
Name: Handset Type, dtype: int64

In [15]:
total_ul_per_user(data)

        MSISDN/Number  Total UL (Bytes)
0        3.360100e+10        36053108.0
1        3.360100e+10        36104459.0
2        3.360100e+10        39306820.0
3        3.360101e+10        20327526.0
4        3.360101e+10        94280527.0
...               ...               ...
106851   3.379000e+10        26716429.0
106852   3.379000e+10        35732243.0
106853   3.197021e+12        37295915.0
106854   3.370000e+14        56652839.0
106855   8.823971e+14        60456049.0

[106856 rows x 2 columns]

In [16]:
total_dl_per_user(data)

        MSISDN/Number  Total DL (Bytes)
0        3.360100e+10      8.426375e+08
1        3.360100e+10      1.207552e+08
2        3.360100e+10      5.566597e+08
3        3.360101e+10      4.019932e+08
4        3.360101e+10      1.363130e+09
...               ...               ...
106851   3.379000e+10      6.879252e+08
106852   3.379000e+10      4.445751e+08
106853   3.197021e+12      1.948281e+08
106854   3.370000e+14      5.396350e+08
106855   8.823971e+14      7.869760e+07

[106856 rows x 2 columns]

In [17]:
total_data_vol(data)

MSISDN/Number
3.360100e+10    8.786906e+08
3.360100e+10    1.568596e+08
3.360100e+10    5.959665e+08
3.360101e+10    4.223207e+08
3.360101e+10    1.457411e+09
                    ...
3.379000e+10    7.146416e+08
3.379000e+10    4.803073e+08
3.197021e+12    2.321240e+08
3.370000e+14    5.962878e+08
8.823971e+14    1.391536e+08
Length: 106856, dtype: float64

In [18]:
total_dur_per_user(data)

        MSISDN/Number  Dur. (ms)
0        3.360100e+10   116720.0
1        3.360100e+10   181230.0
2        3.360100e+10   134969.0
3        3.360101e+10    49878.0
4        3.360101e+10    37104.0
...               ...        ...
106851   3.379000e+10     8810.0
106852   3.379000e+10   140988.0
106853   3.197021e+12   877385.0
106854   3.370000e+14   253030.0
106855   8.823971e+14   869844.0

[106856 rows x 2 columns]

In [19]:
mean_value(data)

../scripts\data_analysis.py:61: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  mean = data[num_list].mean()

Bearer Id                                   1.013887e+19
Start ms                                    4.991882e+02
End ms                                      4.988009e+02
Dur. (ms)                                   1.046086e+05
IMSI                                        2.082016e+14
MSISDN/Number                               4.188282e+10
IMEI                                        4.847455e+13
Avg RTT DL (ms)                             1.097957e+02
Avg RTT UL (ms)                             1.766288e+01
Avg Bearer TP DL (kbps)                     1.330005e+04
Avg Bearer TP UL (kbps)                     1.770429e+03
TCP DL Retrans. Vol (Bytes)                 2.080991e+07
TCP UL Retrans. Vol (Bytes)                 7.596587e+05
DL TP < 50 Kbps (%)                         9.284475e+01
50 Kbps < DL TP < 250 Kbps (%)              3.069355e+00
250 Kbps < DL TP < 1 Mbps (%)               1.717341e+00
DL TP > 1 Mbps (%)                          1.609654e+00
UL TP < 10 Kbps (%)                         9.853014e+01
10 Kbps < UL TP < 50 Kbps (%)               7.767494e-01
50 Kbps < UL TP < 300 Kbps (%)              1.479871e-01
UL TP > 300 Kbps (%)                        7.892285e-02
HTTP DL (Bytes)                             1.144710e+08
HTTP UL (Bytes)                             3.242301e+06
Activity Duration DL (ms)                   1.829177e+06
Activity Duration UL (ms)                   1.408880e+06
Dur. (ms).1                                 1.046091e+08
Nb of sec with 125000B < Vol DL             9.897000e+02
Nb of sec with 1250B < Vol UL < 6250B       3.404344e+02
Nb of sec with 31250B < Vol DL < 125000B    8.108374e+02
Nb of sec with 37500B < Vol UL              1.492571e+02
Nb of sec with 6250B < Vol DL < 31250B      9.654648e+02
Nb of sec with 6250B < Vol UL < 37500B      1.413048e+02
Nb of sec with Vol DL < 6250B               3.719788e+03
Nb of sec with Vol UL < 1250B               4.022083e+03
Social Media DL (Bytes)                     1.795322e+06
Social Media UL (Bytes)                     3.292843e+04
Google DL (Bytes)                           5.750753e+06
Google UL (Bytes)                           2.056542e+06
Email DL (Bytes)                            1.791729e+06
Email UL (Bytes)                            4.673734e+05
Youtube DL (Bytes)                          1.163407e+07
Youtube UL (Bytes)                          1.100941e+07
Netflix DL (Bytes)                          1.162685e+07
Netflix UL (Bytes)                          1.100175e+07
Gaming DL (Bytes)                           4.220447e+08
Gaming UL (Bytes)                           8.288398e+06
Other DL (Bytes)                            4.211005e+08
Other UL (Bytes)                            8.264799e+06
Total UL (Bytes)                            4.112121e+07
Total DL (Bytes)                            4.546434e+08
dtype: float64

In [20]:
median_value(data)

../scripts\data_analysis.py:68: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  median = data[num_list].median()

Bearer Id                                   7.349883e+18
Start ms                                    4.990000e+02
End ms                                      5.000000e+02
Dur. (ms)                                   8.639900e+04
IMSI                                        2.082015e+14
MSISDN/Number                               3.366371e+10
IMEI                                        3.572201e+13
Avg RTT DL (ms)                             4.500000e+01
Avg RTT UL (ms)                             5.000000e+00
Avg Bearer TP DL (kbps)                     6.300000e+01
Avg Bearer TP UL (kbps)                     6.300000e+01
TCP DL Retrans. Vol (Bytes)                 5.687300e+05
TCP UL Retrans. Vol (Bytes)                 2.094950e+04
DL TP < 50 Kbps (%)                         1.000000e+02
50 Kbps < DL TP < 250 Kbps (%)              0.000000e+00
250 Kbps < DL TP < 1 Mbps (%)               0.000000e+00
DL TP > 1 Mbps (%)                          0.000000e+00
UL TP < 10 Kbps (%)                         1.000000e+02
10 Kbps < UL TP < 50 Kbps (%)               0.000000e+00
50 Kbps < UL TP < 300 Kbps (%)              0.000000e+00
UL TP > 300 Kbps (%)                        0.000000e+00
HTTP DL (Bytes)                             1.941949e+06
HTTP UL (Bytes)                             2.297330e+05
Activity Duration DL (ms)                   3.930450e+04
Activity Duration UL (ms)                   4.679350e+04
Dur. (ms).1                                 8.639998e+07
Nb of sec with 125000B < Vol DL             1.280000e+02
Nb of sec with 1250B < Vol UL < 6250B       5.200000e+01
Nb of sec with 31250B < Vol DL < 125000B    1.640000e+02
Nb of sec with 37500B < Vol UL              8.000000e+00
Nb of sec with 6250B < Vol DL < 31250B      2.880000e+02
Nb of sec with 6250B < Vol UL < 37500B      8.000000e+00
Nb of sec with Vol DL < 6250B               2.030000e+02
Nb of sec with Vol UL < 1250B               2.170000e+02
Social Media DL (Bytes)                     1.794369e+06
Social Media UL (Bytes)                     3.292000e+04
Google DL (Bytes)                           5.765829e+06
Google UL (Bytes)                           2.054573e+06
Email DL (Bytes)                            1.793505e+06
Email UL (Bytes)                            4.662500e+05
Youtube DL (Bytes)                          1.161602e+07
Youtube UL (Bytes)                          1.101345e+07
Netflix DL (Bytes)                          1.164222e+07
Netflix UL (Bytes)                          1.099638e+07
Gaming DL (Bytes)                           4.234081e+08
Gaming UL (Bytes)                           8.291208e+06
Other DL (Bytes)                            4.218030e+08
Other UL (Bytes)                            8.267071e+06
Total UL (Bytes)                            4.114331e+07
Total DL (Bytes)                            4.558411e+08
dtype: float64

In [21]:
var_value(data)

../scripts\data_analysis.py:75: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  var = data[num_list].var()

Bearer Id                                   8.370447e+36
Start ms                                    8.329679e+04
End ms                                      8.300026e+04
Dur. (ms)                                   6.567096e+09
IMSI                                        4.617380e+20
MSISDN/Number                               5.989979e+24
IMEI                                        5.024937e+26
Avg RTT DL (ms)                             3.841306e+05
Avg RTT UL (ms)                             7.189942e+03
Avg Bearer TP DL (kbps)                     5.746510e+08
Avg Bearer TP UL (kbps)                     2.139391e+07
TCP DL Retrans. Vol (Bytes)                 3.333054e+16
TCP UL Retrans. Vol (Bytes)                 6.997637e+14
DL TP < 50 Kbps (%)                         1.699903e+02
50 Kbps < DL TP < 250 Kbps (%)              3.862912e+01
250 Kbps < DL TP < 1 Mbps (%)               1.730176e+01
DL TP > 1 Mbps (%)                          2.331818e+01
UL TP < 10 Kbps (%)                         2.147660e+01
10 Kbps < UL TP < 50 Kbps (%)               1.040176e+01
50 Kbps < UL TP < 300 Kbps (%)              2.639076e+00
UL TP > 300 Kbps (%)                        1.678051e+00
HTTP DL (Bytes)                             9.277438e+17
HTTP UL (Bytes)                             3.830101e+14
Activity Duration DL (ms)                   3.244892e+13
Activity Duration UL (ms)                   2.155959e+13
Dur. (ms).1                                 6.567094e+15
Nb of sec with 125000B < Vol DL             6.484787e+06
Nb of sec with 1250B < Vol UL < 6250B       2.089080e+06
Nb of sec with 31250B < Vol DL < 125000B    3.393561e+06
Nb of sec with 37500B < Vol UL              1.486235e+06
Nb of sec with 6250B < Vol DL < 31250B      3.788425e+06
Nb of sec with 6250B < Vol UL < 37500B      9.867436e+05
Nb of sec with Vol DL < 6250B               8.411841e+07
Nb of sec with Vol UL < 1250B               1.032322e+08
Social Media DL (Bytes)                     1.072224e+12
Social Media UL (Bytes)                     3.612348e+08
Google DL (Bytes)                           1.095012e+13
Google UL (Bytes)                           1.415902e+12
Email DL (Bytes)                            1.072963e+12
Email UL (Bytes)                            7.288343e+10
Youtube DL (Bytes)                          4.503173e+13
Youtube UL (Bytes)                          4.026440e+13
Netflix DL (Bytes)                          4.522856e+13
Netflix UL (Bytes)                          4.044311e+13
Gaming DL (Bytes)                           5.952014e+16
Gaming UL (Bytes)                           2.287422e+13
Other DL (Bytes)                            5.914868e+16
Other UL (Bytes)                            2.274340e+13
Total UL (Bytes)                            1.271569e+14
Total DL (Bytes)                            5.960574e+16
dtype: float64

In [22]:
std_value(data)

Bearer Id                                       2893172512268411392.0
Start                                       1 days 17:04:15.227412976
Start ms                                                   288.611834
End                                         1 days 18:20:14.778943351
End ms                                                     288.097653
Dur. (ms)                                                81037.621479
IMSI                                               21488090841.366325
MSISDN/Number                                    2447443358621.665527
IMEI                                              22416372027957.5625
Avg RTT DL (ms)                                            619.782739
Avg RTT UL (ms)                                             84.793524
Avg Bearer TP DL (kbps)                                  23971.878541
Avg Bearer TP UL (kbps)                                     4625.3555
TCP DL Retrans. Vol (Bytes)                          182566527.914748
TCP UL Retrans. Vol (Bytes)                           26453047.172167
DL TP < 50 Kbps (%)                                         13.038031
50 Kbps < DL TP < 250 Kbps (%)                               6.215233
250 Kbps < DL TP < 1 Mbps (%)                                4.159538
DL TP > 1 Mbps (%)                                            4.82889
UL TP < 10 Kbps (%)                                          4.634285
10 Kbps < UL TP < 50 Kbps (%)                                3.225176
50 Kbps < UL TP < 300 Kbps (%)                               1.624523
UL TP > 300 Kbps (%)                                         1.295396
HTTP DL (Bytes)                                      963194563.977449
HTTP UL (Bytes)                                       19570643.166646
Activity Duration DL (ms)                               5696395.46552
Activity Duration UL (ms)                              4643230.599005
Dur. (ms).1                                            81037611.57679
Nb of sec with 125000B < Vol DL                            2546.52444
Nb of sec with 1250B < Vol UL < 6250B                     1445.365032
Nb of sec with 31250B < Vol DL < 125000B                  1842.162008
Nb of sec with 37500B < Vol UL                            1219.112287
Nb of sec with 6250B < Vol DL < 31250B                    1946.387608
Nb of sec with 6250B < Vol UL < 37500B                     993.349688
Nb of sec with Vol DL < 6250B                              9171.60901
Nb of sec with Vol UL < 1250B                            10160.324314
Social Media DL (Bytes)                                1035482.275953
Social Media UL (Bytes)                                  19006.178256
Google DL (Bytes)                                      3309097.017369
Google UL (Bytes)                                      1189916.926004
Email DL (Bytes)                                       1035839.510337
Email UL (Bytes)                                        269969.307031
Youtube DL (Bytes)                                      6710568.85019
Youtube UL (Bytes)                                     6345423.354476
Netflix DL (Bytes)                                     6725218.026494
Netflix UL (Bytes)                                     6359489.759475
Gaming DL (Bytes)                                    243967494.346378
Gaming UL (Bytes)                                      4782699.656232
Other DL (Bytes)                                     243205009.808155
Other UL (Bytes)                                       4769003.686403
Total UL (Bytes)                                      11276386.514689
Total DL (Bytes)                                     244142874.376284
dtype: object

In [23]:
data['dec'] = decile_value(data)
data

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes),dec
0,1.311448e+19,2019-04-04 12:01:00,770.0,2019-04-25 14:35:00,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0,8.0
1,1.311448e+19,2019-04-09 13:04:00,235.0,2019-04-25 08:15:00,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0,8.0
2,1.311448e+19,2019-04-09 17:42:00,1.0,2019-04-25 11:58:00,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0,8.0
3,1.311448e+19,2019-04-10 00:31:00,486.0,2019-04-25 07:36:00,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0,8.0
4,1.311448e+19,2019-04-12 20:10:00,565.0,2019-04-25 10:40:00,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,2019-04-29 07:28:00,451.0,2019-04-30 06:02:00,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0,3.0
149997,7.349883e+18,2019-04-29 07:28:00,483.0,2019-04-30 10:41:00,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0,5.0
149998,1.311448e+19,2019-04-29 07:28:00,283.0,2019-04-30 10:46:00,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0,5.0
149999,1.311448e+19,2019-04-29 07:28:00,696.0,2019-04-30 10:40:00,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0,5.0
150000,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN,NaN